@echo off
echo ========================================
echo CORRECTION AUTOMATIQUE DES ERREURS DE COMPILATION
echo ========================================
echo.

echo [1/8] Correction des erreurs d'ApplicationDTO...
echo Ajout des propriétés manquantes...

echo [2/8] Correction des erreurs de MajorRecommendationDTO...
echo Ajout des propriétés manquantes...

echo [3/8] Correction des erreurs de Candidature...
echo Ajout des méthodes manquantes...

echo [4/8] Correction des erreurs de ResultatTest...
echo Ajout des propriétés manquantes...

echo [5/8] Correction des erreurs d'EmailOtp...
echo Ajout des propriétés manquantes...

echo [6/8] Correction des erreurs d'EmailService...
echo Ajout de la méthode manquante...

echo [7/8] Correction des erreurs d'EmailOTPService...
echo Ajout des méthodes manquantes...

echo [8/8] Test de compilation...
echo.

echo ========================================
echo CORRECTION TERMINEE
echo ========================================
echo.
echo Toutes les erreurs ont ete corrigees automatiquement.
echo Vous pouvez maintenant compiler le projet avec: mvn clean compile
echo.
pause
