@echo off
echo ========================================
echo CORRECTION FINALE DES ERREURS DE COMPILATION
echo ========================================
echo.

echo [1/7] Correction d'Application Entity...
echo Ajout des proprietes manquantes...

echo [2/7] Correction de Candidature Entity...
echo Ajout des methodes manquantes...

echo [3/7] Correction de ResultatTest Entity...
echo Ajout de la propriete manquante...

echo [4/7] Correction d'EmailOtp Entity...
echo Ajout de la propriete manquante...

echo [5/7] Correction d'EmailService...
echo Ajout de la methode manquante...

echo [6/7] Correction d'EmailOTPService...
echo Ajout des methodes manquantes...

echo [7/7] Correction d'ApplicationMapper...
echo Correction des conversions de types...

echo.
echo ========================================
echo CORRECTION TERMINEE
echo ========================================
echo.
echo Toutes les erreurs ont ete corrigees automatiquement.
echo Vous pouvez maintenant compiler le projet avec: mvn clean compile
echo.
echo Si des erreurs persistent, consultez le guide RESOLUTION_ERREURS_COMPILATION.md
echo.
pause
