# Configuration des algorithmes de matching pour l'orientation des étudiants
# Ce fichier peut être surchargé par application.yml ou des variables d'environnement

matching:
  algorithm:
    # Poids des composants de l'algorithme (doit sommer à 1.0)
    euclidean-weight: 0.60      # Distance euclidienne (60% du score final)
    force-analysis-weight: 0.25 # Analyse des forces dominantes (25% du score final)
    critical-pillar-weight: 0.15 # Correspondance des piliers critiques (15% du score final)
    
    # Seuils de qualité des correspondances
    minimum-match-threshold: 0.30    # 30% minimum pour une correspondance valide
    medium-quality-threshold: 0.60   # 60% pour une correspondance de qualité moyenne
    high-quality-threshold: 0.80     # 80% pour une correspondance de haute qualité
    
    # Paramètres de recommandation
    max-recommendations: 3           # Nombre maximum de recommandations à générer
    
    # Paramètres de performance
    enable-caching: true             # Activation du cache pour améliorer les performances
    cache-ttl-seconds: 3600         # Durée de vie du cache (1 heure)
    
    # Paramètres de logging
    enable-debug-logging: false      # Activation des logs de debug
    log-matching-details: true       # Log des détails du matching
    
    # Paramètres de validation
    strict-validation: true          # Validation stricte des profils
    allow-incomplete-profiles: false # Autoriser les profils incomplets
    
    # Paramètres d'optimisation
    enable-parallel-processing: true # Traitement parallèle pour les gros volumes
    max-threads: 4                   # Nombre maximum de threads pour le traitement parallèle

# Configuration des stratégies de matching
strategies:
  euclidean:
    enabled: true
    priority: 1
    description: "Stratégie basée sur la distance euclidienne"
    
  hybrid:
    enabled: true
    priority: 2
    description: "Stratégie hybride combinant plusieurs approches"
    
  simple:
    enabled: false
    priority: 3
    description: "Stratégie simplifiée pour les tests"

# Configuration des calculateurs de scores
calculators:
  euclidean:
    enabled: true
    weight: 0.60
    description: "Calculateur de distance euclidienne"
    
  force-analysis:
    enabled: true
    weight: 0.25
    description: "Analyse des forces dominantes"
    
  critical-pillar:
    enabled: true
    weight: 0.15
    description: "Correspondance des piliers critiques"

# Configuration des moteurs de recommandation
recommendation-engines:
  top3:
    enabled: true
    priority: 1
    description: "Génération des top 3 recommandations"
    
  detailed-analysis:
    enabled: true
    priority: 2
    description: "Analyse détaillée des correspondances"

# Configuration des profils de majeures
major-profiles:
  # Catégories de majeures
  categories:
    - name: "TECHNIQUE"
      description: "Ingénierie, informatique, sciences"
      color: "#2563eb"
      
    - name: "BUSINESS"
      description: "Commerce, gestion, économie"
      color: "#059669"
      
    - name: "SOCIAL"
      description: "Médecine, psychologie, relations humaines"
      color: "#dc2626"
      
    - name: "CREATIF"
      description: "Arts, design, architecture"
      color: "#7c3aed"
      
    - name: "SCIENTIFIQUE"
      description: "Recherche, laboratoire, théorie"
      color: "#ea580c"
  
  # Piliers critiques par catégorie
  critical-pillars:
    TECHNIQUE:
      - "interetScientifiqueTech"
      - "interetLogiqueAnalytique"
      - "competenceResolutionProblemes"
      
    BUSINESS:
      - "interetBusinessGestion"
      - "competenceOrganisation"
      - "competenceCommunication"
      
    SOCIAL:
      - "interetSocialHumain"
      - "valeurImpactSocietal"
      - "competenceCommunication"
      
    CREATIF:
      - "interetArtistiqueCreatif"
      - "valeurInnovationChallenge"
      - "prefTheorieRecherche"
      
    SCIENTIFIQUE:
      - "interetScientifiqueTech"
      - "interetLogiqueAnalytique"
      - "prefTheorieRecherche"

# Configuration des tests et validation
testing:
  enable-mock-data: false           # Activation des données de test
  sample-user-profiles: 5          # Nombre de profils utilisateur de test
  sample-major-profiles: 10        # Nombre de profils majeure de test
  
  # Validation des scores
  expected-score-range:
    min: 0.30                       # Score minimum attendu (30%)
    max: 0.95                       # Score maximum attendu (95%)
    
  # Tolérance pour les tests
  score-tolerance: 0.05            # Tolérance de ±5% pour les tests

# Configuration des métriques et monitoring
monitoring:
  enable-metrics: true              # Activation des métriques
  collect-performance-data: true    # Collecte des données de performance
  
  # Métriques à collecter
  metrics:
    - "matching-execution-time"
    - "score-distribution"
    - "algorithm-usage"
    - "error-rates"
    - "cache-hit-rates"
