# Configuration pour l'envoi d'emails
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:no-reply@diravenir.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

# Configuration de l'application
app:
  email:
    results:
      subject: "Vos résultats d'orientation sont prêts"
    from:
      name: "DirAvenir"
      email: "no-reply@diravenir.com"
    base-url: "https://diravenir.com"
